name: JasonBurns
favicon: null
layout_spectrum: 0.29465464246459305
typography_spectrum: 0.5011901778634638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2649941884446889
  lightness: 0.8017591151874512
  saturation: 0.7662585980724543
  rhythmicContrast: 0.7190811370965093
purpose: []
